# Generated by Django 3.0.1 on 2020-01-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
