# Generated by Django 3.0.1 on 2020-01-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0002_course_material_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
