# Generated by Django 3.0.1 on 2020-01-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_portal', '0004_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
    ]
